### ISSUE TITLE
Yaki Mobile - Error widget when fetch error

### ISSUE THREAD

**Issue by ghost** [XPEHO/YAKI#1027]
** Requirement ** 

As user on the team selection and if i have an error  i want to be able to access at my profile to have my information and be able to disconnect

**To do** 

- [x] On the file features/teamselection/view/teamselection_list i need to update the fail to fetch data line 69 
- [x] add a column with a button to redirect on the profile screen
- [x] I also need to update the back button on the profile screen to redirect on the previous screen

**Comment by LaurentMag** [comment]
the current code removed is the following : 

![Image](https://github.com/XPEHO/YAKI/assets/95299697/0f0ec7da-96d6-42f8-a512-30a050bba335)


![Image](https://github.com/XPEHO/YAKI/assets/95299697/50abf092-ddac-4c70-aa7d-10effd163c9d)

**Comment by LaurentMag** [comment]
context :
With the profil icon set on the team selection, the go back need more work as there is several cases :
- if we come from the teammate summary page, we need to go back to this page
- if we come from the team selection page, we need to go back to this page
before adding back the profil icon we need to correctly handled thoses situation
