### ISSUE TITLE
Yaki Mobile - Forgot password bug

### ISSUE THREAD

**Issue by ghost** [XPEHO/YAKI#1030]
** Requirement ** 

As user i must to be able to use the forgot password function, actually this didn't work

** To do **

Search why we have a regression here

**Comment by LaurentMag** [comment]
Update the user that forwarded the bug finaly. received the mail with the temporary password, but didnt succeed to connect with the temporary password

**Comment by LaurentMag** [comment]
Issue was prior updated to force email and login into lowercase email was create with first letter uppercase, which was creating a conflict in the code
