### ISSUE TITLE
yaki mobile - time declaration

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#1094]
**context**

how long have I been a bug

![Image](https://github.com/XPEHO/YAKI/assets/96787811/8d0e6405-9a28-4227-90bc-d0a49004ccc4)

**TODO**

to analyze

**Comment by LaurentMag** [comment]
review lib, features, team_declaration_summary, view, cell_card.dart

check if stream builder is the appropriate method

**Comment by LaurentMag** [comment]
this was developped
