### ISSUE TITLE
yaki mobile - design basti on the declaration absence

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#1098]
**context**

set up the basty design on the absence declaration
actual design files are in :  **presentation/ui/vacation**

date_picker_popup.dart, (line 36) has the method to send the selected user date to the invoke the notifier createVacationDeclaration method

design actually : 
![Image](https://github.com/XPEHO/YAKI/assets/96787811/7fd08332-c2d8-43a0-b50e-f4bc8be1f50d)

design to setup: 
![Image](https://github.com/XPEHO/YAKI/assets/96787811/e6ffec51-464a-49f4-a485-316a134f65cd)

**Comment by LaurentMag** [comment]
possible library
