### ISSUE TITLE
Be able to modify my status

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#11]
**Is your feature request related to a problem? Please describe.**
As team mate I want to be able to change my status in order to publish to my team my new status

**Describe the solution you'd like**
I can consult the status I have declared for today. I can access to an option to change this status.
When I use this option to change my status I go back to the list of status  and select my new status.
When I select a new status, this status replace the last one I have declared.

**Additional context**
This feature " modify my status" can be used in case of user mistake  or for the MVP to change the status the afternoon if it is not the same as in the morning.

**Comment by MaximeHavez** [comment]
remove or not the the confirmation window ?
