### ISSUE TITLE
Set up of Database

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#12]
**Is your feature request related to a problem? Please describe.**
As developper I want to create the database to save the  teammate status declared by the user of Yaki

**Describe the solution you'd like**
Design the database schema and tables for Yaki.
Take into account the features of future versions (and not only MVP) to avoid heavy refactoring on the database

**Comment by PiotrFLEURY** [comment]
**Table names**

- CAPTAIN
- TEAM
- TEAM_MATE
- DECLARATION
- LOCATION

**Database name**

YAKI

**Comment by FlorianFlouquet** [comment]
Create scripts following scripts:

- [ ] Create database
- [ ] Create table TEAM
- [ ] Create table TEAM_MATE
- [ ] Create table CAPTAIN
- [ ] Create table DECLARATION
- [ ] Create table LOCATION
