### ISSUE TITLE
Develop and provide the API

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#13]
**Is your feature request related to a problem? Please describe.**
As developer I want to create the API to be used by the mobil application

**Describe the solution you'd like**
MVP Features  that will need to use API: 
- authentification to Yaki
- user info 
- declaration info
- team info

**API documentation**
a swagger well documented  will be provided for these API

**Docker**
Create the docker file
Create docker compose

**CI/CD**
Create Github actions CI

**Tests**
Create automated tests

**Database**
The server must be connected to the database to store and fetch data

**Comment by FlorianFlouquet** [comment]
Add the following depedencies:

- [ ] ExpressJs
- [ ] PostgreSql
- [ ] Typescript
