### ISSUE TITLE
Admin back-end - prevent choosed account to be visible in the "invitation list"

### ISSUE THREAD

**Issue by LaurentMag** [XPEHO/YAKI#1359]
![Image](https://github.com/XPEHO/YAKI/assets/95299697/270ea2d3-1af7-4e8d-9682-ad9e64a821ec)

**context**
The list display every account registered in the database.
We might want to hide somes account, such as administrator, or google test account, for them to not be aviable in the list.
`
* Add DB attribute to user table to determine if that user should be returned or not
* Change teammate fetch in teammateJPArepository and captainJPArepository according

**Comment by NyraSama** [comment]
Not needed because we will change the behaviour to display only the company members #1367
