### ISSUE TITLE
Set up the App mobile architecture

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#14]
**Is your feature request related to a problem? Please describe.**
As developper I want to create the shell of the Yaki project to be able to start the developpments of Yaky functionality

**Describe the solution you'd like**
Today there is a simple Repo.
We will create the Mono Repo will contain the fronts (mobile, web ) , back , database).

**Comment by PiotrFLEURY** [comment]
The word "socle" was wrong. I renamed it to "architecture".

To be clear. This ticket is about the Flutter setup :

- create base folders for Flutter front architecture pattern (clean architecture ?)
- state management library => [https://pub.dev/packages/flutter_riverpod](https://pub.dev/packages/flutter_riverpod)
- translation library => [https://pub.dev/packages/easy_localization](https://pub.dev/packages/easy_localization)
- API call library => [https://pub.dev/packages/retrofit](https://pub.dev/packages/retrofit)
- Serialization => [https://pub.dev/packages/json_serializable](https://pub.dev/packages/json_serializable)
- Navigation => [https://pub.dev/packages/go_router](https://pub.dev/packages/go_router)
- etc...

More details here [https://docs.google.com/document/d/1SUoRQeILlw76-o0D9qM-D4vTk12TJkoK3S2vsLgDO10/edit](https://docs.google.com/document/d/1SUoRQeILlw76-o0D9qM-D4vTk12TJkoK3S2vsLgDO10/edit)
