### ISSUE TITLE
Feat / Statistic - Create statistic-type selection dropdown

### ISSUE THREAD

**Issue by NyraSama** [XPEHO/YAKI#1463]
# 🗒️NOTES

# 🏁PREREQUISITES

- [x] **DOR**
- [ ] **DOD**
- [x] End users validation
- [x] Customer validation

# 📜CONTEXT (User Story)

**As a** dev

**I want to** allow the yaki's ui components available to the entire world

**In order to** do this, i need to create a design for a dropdown used to select a statistic-type

# 🪜STEPS TO FOLLOW

- [x] Step 1: Design the dropdown
- [x] Step 2: Ask the end user feedback
- [x] Step 3: Make changes if needed
- [x] Step 4: Make a presentation to the customer
- [x] Step 5: Create the dropdown in yaki_ui
- [x] Step 6: Make a yaki_ui release
- [x] Step 7: Upgrade yaki_ui version in yaki_mobile and yaki_admin
- [x] Step 8: Update and replace statistic-type dropdown in yaki_admin

# ✅ACCEPTANCE CRITERIA

- ✅ The dropdown follows the same idea as Basti UI's yaki design
- ✅ The dropdown follows exactly its initial design
- ✅ The statistic dropdown works as intended in the statistics page

# 📛BLOCKERS
None so far

# 🔍AFFECTED COMPONENT(S) (Scope)
YAKI_UI: InputDropdown element

# ⛓️LINK TO OTHER ISSUES
**YAKI_UI**: https://github.com/XPEHO/yaki_ui/pull/90 (Already merged and released)
**YAKI_ADMIN**: https://github.com/XPEHO/YAKI/pull/1500 

# 🪟SCREEN SHOTS & MOCKUPS
https://github.com/XPEHO/YAKI/assets/15385736/47f2fbbe-aa31-4be0-bd8a-e3259c661cd0

**Comment by Graeimh** [comment]
![Image](https://github.com/XPEHO/YAKI/assets/15385736/f208c34f-fdf3-4879-85b1-62852483a0fd)
Current state of progress. Only a sliding transition and a functionnal scroll bar remains. Tests with selecting API call parameters will follow, along comments.
