### ISSUE TITLE
The superAdmin can manage the teams registered to Yaki

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#15]
**Is your feature request related to a problem? Please describe.**
As super Admin of Yaki , I want to have the possibility to manage the teams that will join Yaki

**Describe the solution you'd like**
A super admin ( only Xpeho guy) will need to 
- create a new team in Yaki
- add /remove new user as teammate in Yaki
- promote a user as captain of its team 

**Describe alternatives you've considered**
You can  : 
- have scripts that allow you to make these management tasks
- create an API that will be used only by super admin 

**Additional context**
In any solution you choose you have to secure the use of super admin functionnality.

**Comment by FlorianFlouquet** [comment]
how do we interact with the api user by super admin ? (admin interface, tools like pgadmin / postman / swagger)
