### ISSUE TITLE
Admin Owner screen

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/YAKI#150]
***Context***
- Currently we do not have an administrator interface to manage clients, captains and teams.

***Expected Behavior***
- We need an interface made in Vue.js consistent with the figma model
- We need to do a CRUD on the TeamMate, Captain, Owner and Customer classes.
- We need to create the missing Owner and Customer tables.

***Acceptance Criteria***
- I must be able to consult on an interface the clients, the captains and the teams

**Comment by LaurentMag** [comment]
admin was developped, this issue isnt relevant anymore
