### ISSUE TITLE
Repository setup

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/YAKI#16]
**Is your feature request related to a problem? Please describe.**
The current repository is empty

**Describe the solution you'd like**
Fill the repository content with application skeleton

**Structure**
This repository will be a mono-repo
Each app part will be contained in a dedicated directory at root level

```bash
.github/
yaki_admin/
yaki_backend/
yaki_database/
yaki_mobile/
CODE_OF_CONDUCT.md
LICENSE
README.md
```

**Additional context**
Mobile front end will be created with Flutter
Web front end will be created with VueJs
Back end will be created with nodeJs
Database will be created with PostgreSQL

**Comment by Graeimh** [comment]
We are making an Open Source project but I can't seem to recall the licence we agreed on using.

Do we have a specific Code of Conduct/Readme structure already available for Yaki?

**Comment by PiotrFLEURY** [comment]
Yes we do

Just open the main page of the repository.

License is here [https://github.com/XPEHO/YAKI/blob/main/LICENSE](https://github.com/XPEHO/YAKI/blob/main/LICENSE)

Code of conduct is here [https://github.com/XPEHO/YAKI/blob/main/CODE_OF_CONDUCT.md](https://github.com/XPEHO/YAKI/blob/main/CODE_OF_CONDUCT.md)

A contributing file will be created in order to explain how contributions should be done

**Comment by PiotrFLEURY** [comment]
Contribution proposal => https://github.com/XPEHO/YAKI/pull/19
