### ISSUE TITLE
Admin Captain Teammate view

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#289]
**Context**

As a captain I can see each teammate of the team.

**Expected Behavior**

When I connect to the admin interface I must be able to see a teammate in my team.

**Acceptance Criteria**

The teammate must looks like as in the figma model.

**Comment by HaddoucheRym** [comment]
I made the following changes to the Yaki_backend_admin:

- Modified the SQL query in `**teamMateRepository**` for the `**findAllByTeam**` methodI to retrieve the `**lastName**`, `**firstName**`, and `**email**` of a `**teamMate**`. 
- Modified the `**findAllByTeam**` method in `**teamMateService**`
- Modified the JUnit unit test for the `**findAllByTeam**` method
