### ISSUE TITLE
Away until

### ISSUE THREAD

**Issue by EstelleHisXpeho** [XPEHO/YAKI#32]
**Description**
As a teammate, I want to be able to declare me out of office until a date 
to not be disturbed during my vacation

**Additional informations**
When I select the "away" status , a popin prompts the returning date

**Technical  precision** 
Recommend to use a date picker

**mokups**
 _add link here_

**Comment by MaximeHavez** [comment]
We have had feedback from the end user about this

**Comment by LaurentMag** [comment]
made with the #737
