### ISSUE TITLE
pop-up cancel

### ISSUE THREAD

**Issue by StephanieGodin** [XPEHO/YAKI#324]
Context
User dupond is logged and he has to choose a team after his declaration but he go back thinking that his declaration was upadated.

Expect Behaviour
As user like dupond
i want to select my team on the popup
so that i have to choose an team necesseraly

Criteria acceptance
if i don't choose an equipe, yaki don't register my update
if i click on cancel, a popup message appears to indicate that I have to choose a team to register and that it has not been registered

**Comment by LaurentMag** [comment]
workflow change with bastiUI
