### ISSUE TITLE
Summary of presential

### ISSUE THREAD

**Issue by StephanieGodin** [XPEHO/YAKI#327]
Context
User wants to see the summary of presential of the day to verify my declaration

Expected behaviour
As user like 'dupond'
I want to see a summary of my presential days
As that to know if my information are exact

Criteria Acceptance
Scenario 1 : see summary of presential
I am user and i connect my name / password
When i click on human picto
then i see a presential summary

**Comment by profotoce59** [comment]
To discuss

**Comment by profotoce59** [comment]
duplicate #700
