### ISSUE TITLE
change your declaration

### ISSUE THREAD

**Issue by StephanieGodin** [XPEHO/YAKI#328]
Context
I want to change my presential day but i don't know how to make this

Expected Behaviour
As user like 'dupond'
I want to see a message near the weather picto information to explain me how to do
so that i change my declaration of presential day

Acceptance criteria
show a message near the picto

Additionnal informations
Design informations

**Comment by StephanieGodin** [comment]
![Image](https://user-images.githubusercontent.com/132360026/235699631-565b0204-566f-498e-a388-dd46974144a5.jpg)



![Image](https://user-images.githubusercontent.com/132360026/235699830-fc0429c4-703b-4cee-b2fd-0505fcf10b59.jpg)

**Comment by LaurentMag** [comment]
will be changed with bastiUI  design
