### ISSUE TITLE
Picto on top on the right with a human

### ISSUE THREAD

**Issue by StephanieGodin** [XPEHO/YAKI#329]
Context
I want to personnalize the picto on top of the app mobile, so i can choose between different picto

Expected behaviour
As user like 'dupond'
I want to change my picto on top on the right
As that to put a woman or a dog or a flower picto

Additionnal informations
Create different picto
How can i change it
Depends on #331

**Comment by StephanieGodin** [comment]
![Image](https://user-images.githubusercontent.com/132360026/235702273-b3739b2b-0e49-4504-83a3-8333eb90b978.jpg)

**Comment by LaurentMag** [comment]
will be changed bastiUI
