### ISSUE TITLE
Create a user worklow : the owner

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#354]
**Context**

As a yaki team 
I want to be able to execute the owner journey prototype on figma for the web app.
In order to understand how we will develop our functionnalities.

**Expected Behavior**

Create the figma prototype of the owner on the web app

**Acceptance Criteria**

Every functionnality of the owner can be used on the figma on the web app

**Comment by LaurentMag** [comment]
will be made by bastiUI
