### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#360]
Context

As a user,
I want to be redirected to a custom error page,
In order to be able to understand what is the error and report it.

Expected Behavior

Create a new error page that handle each type of error.

Acceptance Criteria

I need to be redirected to this error page if an error is happening.

**Comment by LaurentMag** [comment]
The mobile currently have distinct error message, this should be handled with the new bastiUI design for the administration

**Comment by LaurentMag** [comment]
Custom error page are developped
