### ISSUE TITLE
Add a change in back admin for the display status of the user's invitation

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#385]
Context

The captain/owner/customer want to see the status of his application sent to a future user

Expected Behavior

we need to see the status of the user so we add an invitation table with a pending or ok status
the test karaté and JUNIT are passed

Acceptance Criteria

the status display

The admin front is done,
We need a feature to send a notification to the corresponding user on his mobile app, Once he accepts, the status must change.
Second option, he can invite the user by email if he is not in the list of user.
The workflow is still to discuss, how the person will be able to accept the invitation by linking his account. (token of the team or the full inscription process)

**Comment by LaurentMag** [comment]
This was set with basiUI design, annd the invitation status is designed to be used with email invitation.
Could need to recreate a corresponding ticket
