### ISSUE TITLE
create form signup web

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#392]
**context**
as a captain/customer
i want to have a form for signup 
in order to have a personal account on Yaki

**expected behavior**
I want in my form: 
- name (varChar),
- firstname(varChar),
- login,
- email(email@example.com), 
- password, confirm password (My password must contains  minimum 12 characteres with minimum one number, one special character.)

I want to be able to see my password
I want a confirmation signup
I want a button confirmation to sent the form

If my informations are poorly filled, I want error messages.

Then, I am redirected on home page.

**acceptance criteria**
I can signup.
The confirm message show up.
The data are in database.
Test to signup with wrong data in each fields to see if the error message correctly show up.
I'm successfully redirected in the sign in page

**Comment by profotoce59** [comment]
to discuss with the owner.
Do we need an account registration specific for the customer, or a Contact me page with an explaination on how to create a Customer account is sufficient. We will need to add it manually on our own

**Comment by profotoce59** [comment]
the signup will be avalaible only on the mobile app
