### ISSUE TITLE
documentation of update of UAT

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#395]
**Context**
As developer
I want documentation which explain how to update UAT 
In order to  update UAT by myself.

**Expected behavior**
the documentation is understandable and accessible easily.
with the other documentation in Yaki - Google Drive.

**Acceptance criteria**
i am able to update UAT by following the documentation.

**Comment by profotoce59** [comment]
CD restart UAT at each push, if we want manual update, only the "VIP" can have access to this feature
