### ISSUE TITLE
Declaration

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/YAKI#4]
**Description**
As a teammate I want to declare my current working mode to the team in order to inform the captain

**Additional informations**
Declaration screen can be opened by the teammate initiative or by clicking on a received captain notification
Declaration will be stored into the app and will be available for the captain on demand

![Image](https://user-images.githubusercontent.com/25879276/198250958-43af2ec1-487a-4d66-aaca-5d0ef377b5f5.png)

**Comment by HaddoucheRym** [comment]
the captain notification part will be handled in the #30 ticket.
