### ISSUE TITLE
Create a CD workflow to publish on the prod server

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#401]
**Context**

As a developper
I want to have have a CD 
In order to be able publish a new version of my application on the prod server in one click.

**Expected Behavior**

Create a worklow

**Acceptance Criteria**

We must click on the button to publish the application on the production server.

**Ressources**

We need the help of an admin in order to create the securized connection with the secrets between the prod server and the CD.

**Comment by LaurentMag** [comment]
this was created
