### ISSUE TITLE
mail more pleasant, for the confirmation to register

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#590]
there is a link in the email sent, this link redirect to a page with only text.
make a nice visual, and redirect to the good page if possible.

We have to redirect the mail to teh front admin, the front admin will make an API call in order to verify the token so the user account is verified or not.
There is also a problem with nginx where a 404 error is sent when we call the new ui-route, it's the same error as when we try to refresh a page.

**Comment by LaurentMag** [comment]
proposition Didier :

Je propose :
1) Après inscription. A la place de "Please follow the link below to verify your email address. If your email address is not verified in 24 hours, your account will be deleted.
Confirm Registration"
Bien entendu, maj le token


====================
<div style="max-width: 560px; padding: 20px; background: #ffffff; border-radius: 5px; margin: 40px auto; font-family: Open Sans,Helvetica,Arial; font-size: 15px; color: #666;">
<div style="color: #444444; font-weight: normal;">
<div style="text-align: center; font-weight: 600; font-size: 26px; padding: 10px 0; border-bottom: solid 3px #eeeeee;">YAKI</div>
<div style="clear: both;"> </div>
</div>
<div style="padding: 0 30px 30px 30px; border-bottom: 3px solid #eeeeee;">
<div style="padding: 30px 0; font-size: 24px; text-align: center; line-height: 40px;">Thank you for signing up!<span style="display: block;">Please click the following link to activate your account.</span><span style="display: block;">If your email address is not verified in 24 hours, your account will be deleted.</span></div>
<div style="padding: 10px 0 50px 0; text-align: center;"><a style="background: #555555; color: #fff; padding: 12px 30px; text-decoration: none; border-radius: 3px; letter-spacing: 0.3px;" href="{account_activation_link}">Activate your Account</a></div>
<div style="padding: 15px; background: #eee; border-radius: 3px; text-align: center;">Need help? <a style="color: #3ba1da; text-decoration: none;" href="mailto:[yaki@xpeho.fr](mailto:yaki@xpeho.fr)">contact us</a> today.</div>
</div>
<div style="color: #999; padding: 20px 30px;">
<div>Thank you!</div>
<div>The <a style="color: #3ba1da; text-decoration: none;" href="https://www.xpeho.com/yaki">YAKI</a> Team</div>
</div>
</div>



2) après confirmation du lien. A la place de "Your account has been verified, you can now access to your account on the mobile application with your credential"

<div style="max-width: 560px; padding: 20px; background: #ffffff; border-radius: 5px; margin: 40px auto; font-family: Open Sans,Helvetica,Arial; font-size: 15px; color: #666;">
<div style="color: #444444; font-weight: normal;">
<div style="text-align: center; font-weight: 600; font-size: 26px; padding: 10px 0; border-bottom: solid 3px #eeeeee;">YAKI</div>
<div style="clear: both;"> </div>
</div>
<div style="padding: 0 30px 30px 30px; border-bottom: 3px solid #eeeeee;">
<div style="padding: 30px 0; font-size: 24px; text-align: center; line-height: 40px;">Your account has been verified.<span style="display: block;">You can now access to your account on the mobile application with your credential.</span></div>
<div style="padding: 15px; background: #eee; border-radius: 3px; text-align: center;">Need help? <a style="color: #3ba1da; text-decoration: none;" href="mailto:[yaki@xpeho.fr](mailto:yaki@xpeho.fr)">contact us</a> today.</div>
</div>
<div style="color: #999; padding: 20px 30px;">
<div>Thank you!</div>
<div>The <a style="color: #3ba1da; text-decoration: none;" href="https://www.xpeho.com/yaki">YAKI</a> Team</div>
</div>
</div>
