### ISSUE TITLE
admin-front If a user have more than one customer, add one tab for each customer

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#642]
**Context**
As a captain, a customer
I want to be able to choose the customer
when I create a new team.
On the admin view.
Because if a captain is in two different company, we have to know in which company the team is. And it's teh same for all the action effectued on the admin.

**Expected Behavior**
Create different tab for each customer, it will be easier for the user to navigate, and easier in UI/UX design
Wait for the UI/UX designer for his point of view.

If I'm on one tab I should not be able to see my tab of my others customers.

**Comment by LaurentMag** [comment]
this is not relevant anymore with the new design
