### ISSUE TITLE
Customer page functionalities : add captain / create team

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#687]
**context**
As a customer 
I want to be able to add a captain to my captain list.
And also to be able to create a new team, 
And assign a captain to this team
In order to manage my teams.

**expected behaviour**
So to create a team I will create the team, invite a user to promote it as a captain, and in the team I just created, assign a captain to my team from my captain list.

**************************************************************
the backend is almost done we just need one route to assign a captain to a team, the rest of the work is on the front part.
*************************************************************

**Comment by profotoce59** [comment]
the route is done #722
