### ISSUE TITLE
mobile - declaration summary

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#700]
I could do some mistake during my declaration, so a button to see a summary of my declaration for the day and all the declaration made to come (vacation) could be very helpful.
UseCase : 
I declare myself for the day in remote then I want to declare my future holidays.
But i just made a mistake and select today for the start.
So I modify my declaration by clicking on the button CHANGE to say that I will go on vacation next week. 

The current backend mobile will save all my declaration, so only the last declaration made will override the previous one if they have the same declaration time : so my error will override my declaration for the day. And my captain will se me as absent for the day.

Add a possibility to clear a declaration in this summary.

- mobile front + fetch
- nodejs query

**Comment by SDecambray** [comment]
I think we already did this with the new query

**Comment by LaurentMag** [comment]
Not in the bastiUI design
