### ISSUE TITLE
mobile - absence : should handle halfday

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#712]
For long absence we should be able to select morning or afternoon for the start and absence end.
We should also be able to declare a halfday absence of a selected day
return date, 
add two buttons to switch mode for the person that will comme back from an absence at midday or be absent from miday.

**Expected Behavior**

We should not be able to choose a previous date from the one selected for the beginning date
syncFusion_flutter_datePicker. flutter date range picker

**Comment by LaurentMag** [comment]
This is planned with BastiUI design
