### ISSUE TITLE
mobile_api : declaration type should be different from declaration type coming from DB response

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#713]
When creating a declaration in the mobile, the object send do not have declarationId attribut.
But in the API there is only one declaration Type used for declaration coming from the front end, and for DB query response, which do return an object with the declarationID

For this reason there should be another object created and used to Type data coming from the mobile, without declaration ID

**Comment by LaurentMag** [comment]
this was made during TS duck typing security issue resolution
