### ISSUE TITLE
CI/CD prod incremental versionning ?

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#718]
**Current Behavior**
the CI publish the docker image under the same name on github : admin-front-prod, so it erase the previous version of the prod.
**Expected Behavior**
We can use incremential version, so at each new release of the produciotn, a new tag is generated with the new version. That means :
Should we keep track of every image on github because they will stay, is there a limited storage on github, could we store those images in another place, so we could delete them on github ?
How to tell to the production to pull the image with the right name ???

**Comment by LaurentMag** [comment]
was developped
