### ISSUE TITLE
admin-ui can't refresh the page without loosing informations

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#727]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:*
In dev mode
1. Go to YAKI_ADMIN
2. Connect to the application
3. F5
4. The pinia store loose their stored data

**Expected behavior**
The page must looks like as before the F5

**Additional context**
[Add any other context about the problem here.](https://github.com/vuejs/pinia/issues/309)

**Comment by LaurentMag** [comment]
this is not relevant anymore as the refresh is locked by NGINX
