### ISSUE TITLE
admin-front confirmation to grant admin rights

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#733]
**Context**
As a administrator with customers rights, when I want to give admin rights to another person, I should have a modal to confirm that I want grant him rights.

[X] Is the request has enough explanations, and is understood by everybody.

[X] Issue priority was review by the team.

[X] buisiness logic has been studied.

[X] Backlog item has been studied and reviewed by the team during refinement.

[X] If a issue depend on another(s) one(s), this/thoses issue(s) are indicated in the issue.

[X] Use case are clear.

[X] We do have maquette / prototype / story board to understand the impacted user flow of the screen we are working on.

[X] We understand all technical task involved for the issue realization.

[X] Acceptances criteria are limpid.

[X] We know how to test the issue once coded (at least manual).

[] We have identified the automated test to release.

[X] We have estimated issue size.

[X] The back log item is feasible in one sprint, if not it need to be refined

**Comment by LaurentMag** [comment]
This need to be review with the new design

**Comment by LaurentMag** [comment]
There is no more admin right setup with the bastiUI design
