### ISSUE TITLE
Implement all the button to access to future functionnalities.

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#738]
We want to have a global view of the application in order to see what will be implemented and to see the final design.
When we clik on those button, we should be redirect to a âge that said, this functionnality is not implemented yet.
Think to implement that on the future design of the application mobile and desktop.

example: extraction csv, change picture profil, traçability, customization. ->go to a single page with page under construction

design + single page under construction

**Comment by LaurentMag** [comment]
another ticket was made for this issue and will be handled in the spring 22
