### ISSUE TITLE
profil photo for user customizable

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#808]
**Context**
As a user I want to change my profil photo in order to be recognize by my other teammate.

On the mobile application, in our profil page, we should be able to click on your image and upload an image from your device or computer for the PWA from the computer.
We also need to change the database in order to save the photo of the user
Think to the resize of the image : https://www.fluttercampus.com/guide/358/resize-image-flutter/

To see the library: https://pub.dev/packages/image_picker

**Comment by LaurentMag** [comment]
Create a blob (binary) for picture that will be saved in the database. (limite size, check for file type : png....)
In hibernate its Lob()

Else file system outside of the container 
* file system : store in disk given then path : /users/yyyy/mm/jj/serialNumber/avatar.jpg/png/svg.... etc 
( 1000 files per repertories )

* Create a Avatar table ( userId/ type(svg, png..etc) / avatar binary[] 
yet the issue can be related to dumb when there is too much user

**Comment by SDecambray** [comment]
Need to create a table named : Avatar with an id, userId, picture: blob, bastiAvatar: blob, isBasti(bool), isValid(bool).
When a picture is send, check if  isvalid True change when  change basti false. if he using a bastiAvatar isBasti must be true

**Comment by LaurentMag** [comment]
BDD ET BACK : 

- how to convert image as blob
- how to limit image size and format in flutter
- create new table
- create enum in user table (basti avatar + personal avatar ID)
- Create back end route
- 1 back query to edit enum
- 1 back query add blob + set isValide false
- use user info GET add avatar info from ENUM
- SERVICE logic

FRONT 

- RETROFIT + RIVERPOD user info used for profil page
- add information related to blob
- convert blob to image 
- Display
- ADD personal picture slot 

When open the profil page, fetch, if personal picture is still false => display a pending (or similar info) else still display the picture but add filter on top

**Comment by PriscilliaAmmeux** [comment]
migration script

**Comment by LaurentMag** [comment]
suggestions to resize photo with flutter : 
https://pub.dev/packages/image
https://www.fluttercampus.com/guide/358/resize-image-flutter/#how-to-resize-image-in-flutter
