### ISSUE TITLE
Add test for mobile

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/YAKI#86]
**Context**
- Actually, the Frontend have not tests

**Expected Behavior**
- Setup unit test

**Acceptance criteria**
- Min. 50% coverage validated in the CI

**Comment by MaximeHavez** [comment]
Test unitaire : https://docs.flutter.dev/testing
Golden Test : https://medium.com/flutter-community/flutter-golden-tests-compare-widgets-with-snapshots-27f83f266cea
