### ISSUE TITLE
The Captain mobile view

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/YAKI#9]
**Description**
As a captain I want to consult all the teammates declarations of the day in order to see their statuses and check who didn't made it's declaration yet

**Additional informations**
Captain is the team manager
Declaration list will contain for each row: Teammate name and avatar, declaration status (icon + label), declaration date with hour

**Comment by FlorianFlouquet** [comment]
Add a field to filter the team mates by name and status (ask client about this feature)

**Comment by LaurentMag** [comment]
- A component card
- A map function to display teamate list
- filter 

- Filter logic in API or front ? 

- get all teamate

- teamate limit ? ( sprint review 2 )
