### ISSUE TITLE
mobile -profil page - avatar - save avatar

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#926]
I need to choose my avatar and I want to save this for the latest connexion: 

[ ] to add a column to BDD : first in local  
[ ] and in true BDD (a person to access to true BDD),
[ ] set the save system to the chosen image link DB (with provider -> notify -> repo -> api )
[ ] sharedPereference can be used to save the image (link)

**Comment by LaurentMag** [comment]
this is handled in the ticket [#808](https://github.com/XPEHO/YAKI/issues/808)
