### ISSUE TITLE
mobile - fix fetch profil page

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#952]
**Requirement**
the informations in profils page are lost when we are also connected. Look the provider for fix that. we need to get the information of user everytime to display them to the profile input and disabled the input for firstname lastname and email.

**To do**

We must fetch the user information on the profile page to display, we must create a endpoint with based on userId and don't save them to the sharedpref

**Comment by PriscilliaAmmeux** [comment]
2 solutions : 

- create new endpoint who with userId and token in header get the fetch the informations of this user
- to the connection, save the user informations in shared preferences

**Comment by SDecambray** [comment]
Error to fix :

Actually the user didn't see his information the first time
Propably the fetch happen after the initialization of the screen, that why we need to be sure the information is fetch before show the screen
