### ISSUE TITLE
mobile - fix background profil page

### ISSUE THREAD

**Issue by PriscilliaAmmeux** [XPEHO/YAKI#958]
the background of figma: 

![Image](https://github.com/XPEHO/YAKI/assets/96787811/12c9d99a-08f3-4757-897f-9ba03d3e7ec5)

background to uat: 

![Image](https://github.com/XPEHO/YAKI/assets/96787811/0c3ba118-a81d-4476-92bf-442f5f0228ef)

**Comment by LaurentMag** [comment]
not necessary to change now
