### ISSUE TITLE
mobile - user teams + the corresponding teammates and their declaration

### ISSUE THREAD

**Issue by SDecambray** [XPEHO/YAKI#972]
Currently the Express query in **teammate.repository.ts** files, only retrive the current day declaratons on the differentes teammates.
While we should retrive the entier list of teammates even if they dont have declaration, in this situation the declaration related attributes should be null to indicate in the mobile teams declaration summary that thoses user arent yet declared

**Comment by LaurentMag** [comment]
this was made
